#!/usr/bin/ruby

require 'rubygems'
require 'ansi'

class String
  include ANSI::Mixin
end

spec = Gem::Specification::load("cf_deployer.gemspec")
puts "Building Gem version #{spec.version.to_s.yellow} at #{Time.now.strftime('%b %e, %l:%M %p').yellow}..."
system('gem build cf_deployer.gemspec')
system("gem install cf_deployer-#{spec.version}.gem --ignore-dependencies --no-document")